import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBn/+51wx
ST6ckGT8J94pOgAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIHnDY85NMQjx6Ter
yLeCC+DSqMtFjN0YEfcHJ+Z22cF3AAAAkL9VDnmXvjny+Uf7wbKVVq4SrBFc+5tHDTR0d/
YVwfy791IlEBI+WkFJxtrHhOeDDos9D6WBGmKj9hPpGf6GeXcEkl3IBXZMUzJZXmLfVyon
s39tVHTawx6/a2jMfAkm7NQs0TypHgIJk7cSUdvgd203VaoIC0/ENbpTnjvLS3Y714WgSf
0XKeFkGoPfQW8S3Q==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
